Revert "net-misc/routinator: add 0.13.0"
This reverts commit 7031df13e52e1f8e70b5c5de8fcd223f00f43692.

Can’t build offline
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("github.com")), port: None, path: "/NLnetLabs/routinator-ui/releases/download/v0.3.4/routinator-ui-build.tar.gz", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" })) }', /var/tmp/portage/net-misc/routinator-0.13.0/work/cargo_home/gentoo/routinator-ui-0.3.4/build.rs:216:73